/**
 * AGENTS.md overlay generator for oh-my-ghcopilot (OMGHC).
 *
 * Ported from OMX `src/hooks/agents-overlay.ts` (Yeachan Heo et al., MIT) and
 * trimmed to the OMGHC M2b contract. The full OMX implementation pulls in
 * codebase-map, explore-routing, planning-artifact, and skill-active state
 * sources that are not yet ported. This module preserves the marker-bounded
 * idempotent apply/strip semantics so a future iteration can re-introduce
 * those producers without changing the overlay contract.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const DEFAULT_MARKERS = {
  start: "<!-- OMGHC:AGENTS:START -->",
  end: "<!-- OMGHC:AGENTS:END -->",
} as const;

export interface OverlayMarkers {
  start: string;
  end: string;
}

export interface OverlayInput {
  projectRoot: string;
  agentsTemplate?: string;
  managedMarkers?: OverlayMarkers;
}

export interface OverlayOutput {
  full: string;
  managedOnly: string;
}

export interface WriteOverlayResult {
  written: boolean;
  reason?: string;
}

function packageRoot(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  return resolve(here, "..", "..");
}

function defaultTemplatePath(): string {
  return join(packageRoot(), "templates", "AGENTS.md");
}

function readTemplate(templatePath: string): string {
  if (!existsSync(templatePath)) {
    throw new Error(`AGENTS.md template not found: ${templatePath}`);
  }
  return readFileSync(templatePath, "utf-8");
}

function buildManagedSection(projectRoot: string): string {
  const lines = [
    "<!-- Auto-generated by OMGHC. Do not edit by hand. -->",
    `**Project root:** \`${projectRoot}\``,
    "**Note:** Hooks do not fire in Copilot v1.0.40; this overlay is forward-compatible with Copilot native hook support.",
  ];
  return lines.join("\n");
}

function escapeRe(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function stripExistingManagedSection(
  content: string,
  markers: OverlayMarkers,
): string {
  const re = new RegExp(
    `${escapeRe(markers.start)}[\\s\\S]*?${escapeRe(markers.end)}\\n?`,
    "g",
  );
  return content.replace(re, "");
}

function injectManagedSection(
  content: string,
  managedSection: string,
  markers: OverlayMarkers,
): string {
  const stripped = stripExistingManagedSection(content, markers);
  const block = `${markers.start}\n${managedSection}\n${markers.end}`;
  const trimmedTail = stripped.replace(/\s+$/, "");
  return `${trimmedTail}\n\n${block}\n`;
}

/**
 * Generate the AGENTS.md overlay. Returns the full document (template + managed
 * section) and the managed-section content alone.
 */
export function generateOverlay(input: OverlayInput): OverlayOutput {
  const markers = input.managedMarkers ?? DEFAULT_MARKERS;
  const templatePath = input.agentsTemplate ?? defaultTemplatePath();
  const template = readTemplate(templatePath);
  const managedOnly = buildManagedSection(input.projectRoot);
  const full = injectManagedSection(template, managedOnly, markers);
  return { full, managedOnly };
}

/**
 * Write the generated overlay to `targetPath`. Idempotent: if the target file
 * already contains an identical managed section, returns `{ written: false }`.
 */
export function writeOverlayToFile(
  input: OverlayInput,
  targetPath: string,
): WriteOverlayResult {
  const markers = input.managedMarkers ?? DEFAULT_MARKERS;
  const { full, managedOnly } = generateOverlay(input);

  let output = full;
  if (existsSync(targetPath)) {
    const current = readFileSync(targetPath, "utf-8");
    if (current.includes(`${markers.start}\n${managedOnly}\n${markers.end}`)) {
      return { written: false, reason: "managed section already up to date" };
    }
    output = injectManagedSection(current, managedOnly, markers);
  }

  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, output, "utf-8");
  return { written: true };
}

/**
 * Pure helper exposed for tests / callers that only need to remove the managed
 * section without rewriting the file.
 */
export function stripManagedSection(
  content: string,
  markers: OverlayMarkers = DEFAULT_MARKERS,
): string {
  return stripExistingManagedSection(content, markers);
}
